# ⬇️ ⬇️ ⬇️ 이 부분을 추가하세요 ⬇️ ⬇️ ⬇️
logging:
  level:
    org.springframework.security.oauth2: TRACE
    org.springframework.web.reactive.function.client: TRACE
# ⬆️ ⬆️ ⬆️ 이 부분을 추가하세요 ⬆️ ⬆️ ⬆️


spring:
  # 1. MySQL DB ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/breadfeet?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root # ?? DB ??
    password: 1234 # ?? DB ????

  # 2. JPA ??
  jpa:
    hibernate:
      ddl-auto: update # (??) ? ?? ? User ???? ?? ??? ?? ??/??
    properties:
      hibernate:
        format_sql: true # SQL ??? ??? ??
    show-sql: true # ?? ?? ??

  # 3. OAuth2 ????? ?? (???)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "e5655138fc54844b5719e31d08e9a727"
            client-secret: "RLdqBGt3NSQCjxYru94edyXfaxaVpM4o"
            client-authentication-method: client_secret_post
            scope: profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id